<?xml version="1.0" encoding="utf-8"?><Database Name="OrderManagement" Class="OrderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ADMIN-PC\SQLEXPRESS;Initial Catalog=OrderManagement;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OrderManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.orderitem" Member="orderitems">
    <Type Name="orderitem">
      <Column Name="intOrderItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vcName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="intWeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vcImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intStockKeepingUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vcBarcode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intAvailableQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="orderitem_order" Member="orders" ThisKey="intOrderItemID" OtherKey="intOrderItem" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="orders">
    <Type Name="order">
      <Column Name="intOrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vcBuyerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vcBuyerPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcBuyerEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcShippingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intOrderStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intOrderItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="orderitem_order" Member="orderitem" ThisKey="intOrderItem" OtherKey="intOrderItemID" Type="orderitem" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spdisplay_allorders" Method="spdisplay_allorders">
    <ElementType Name="spdisplay_allordersResult">
      <Column Name="intOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vcBuyerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vcBuyerPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcBuyerEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcShippingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intOrderStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intOrderItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spdisplay_spcificorder" Method="spdisplay_spcificorder">
    <Parameter Name="intOrderID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spdisplay_spcificorderResult">
      <Column Name="intOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vcBuyerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vcBuyerPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcBuyerEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vcShippingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intOrderStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intOrderItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spdelete_order" Method="spdelete_order">
    <Parameter Name="intOrderID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spupsert_order" Method="spupsert_order">
    <Parameter Name="buyerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="buyerPhone" Type="System.Int32" DbType="Int" />
    <Parameter Name="buyerEmail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="shippingAddress" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="orderStatus" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="orderItem" Type="System.Int32" DbType="Int" />
    <Parameter Name="orderQunatity" Type="System.Int32" DbType="Int" />
    <Parameter Name="existOrderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="orderID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>