#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OrderManagement")]
	public partial class OrderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertorderitem(orderitem instance);
    partial void Updateorderitem(orderitem instance);
    partial void Deleteorderitem(orderitem instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    #endregion
		
		public OrderDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OrderManagementConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<orderitem> orderitems
		{
			get
			{
				return this.GetTable<orderitem>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spdisplay_allorders")]
		public ISingleResult<spdisplay_allordersResult> spdisplay_allorders()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spdisplay_allordersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spdisplay_spcificorder")]
		public ISingleResult<spdisplay_spcificorderResult> spdisplay_spcificorder([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intOrderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intOrderID);
			return ((ISingleResult<spdisplay_spcificorderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spdelete_order")]
		public int spdelete_order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intOrderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intOrderID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spupsert_order")]
		public int spupsert_order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string buyerName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> buyerPhone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string buyerEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string shippingAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string orderStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orderItem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orderQunatity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> existOrderID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buyerName, buyerPhone, buyerEmail, shippingAddress, orderStatus, orderItem, orderQunatity, existOrderID, orderID);
			orderID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderitem")]
	public partial class orderitem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _intOrderItemID;
		
		private string _vcName;
		
		private System.Nullable<int> _intWeight;
		
		private System.Nullable<int> _intHeight;
		
		private string _vcImage;
		
		private System.Nullable<int> _intStockKeepingUnits;
		
		private string _vcBarcode;
		
		private System.Nullable<int> _intAvailableQuantity;
		
		private EntitySet<order> _orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnintOrderItemIDChanging(int value);
    partial void OnintOrderItemIDChanged();
    partial void OnvcNameChanging(string value);
    partial void OnvcNameChanged();
    partial void OnintWeightChanging(System.Nullable<int> value);
    partial void OnintWeightChanged();
    partial void OnintHeightChanging(System.Nullable<int> value);
    partial void OnintHeightChanged();
    partial void OnvcImageChanging(string value);
    partial void OnvcImageChanged();
    partial void OnintStockKeepingUnitsChanging(System.Nullable<int> value);
    partial void OnintStockKeepingUnitsChanged();
    partial void OnvcBarcodeChanging(string value);
    partial void OnvcBarcodeChanged();
    partial void OnintAvailableQuantityChanging(System.Nullable<int> value);
    partial void OnintAvailableQuantityChanged();
    #endregion
		
		public orderitem()
		{
			this._orders = new EntitySet<order>(new Action<order>(this.attach_orders), new Action<order>(this.detach_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderItemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int intOrderItemID
		{
			get
			{
				return this._intOrderItemID;
			}
			set
			{
				if ((this._intOrderItemID != value))
				{
					this.OnintOrderItemIDChanging(value);
					this.SendPropertyChanging();
					this._intOrderItemID = value;
					this.SendPropertyChanged("intOrderItemID");
					this.OnintOrderItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcName", DbType="NVarChar(50)")]
		public string vcName
		{
			get
			{
				return this._vcName;
			}
			set
			{
				if ((this._vcName != value))
				{
					this.OnvcNameChanging(value);
					this.SendPropertyChanging();
					this._vcName = value;
					this.SendPropertyChanged("vcName");
					this.OnvcNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWeight", DbType="Int")]
		public System.Nullable<int> intWeight
		{
			get
			{
				return this._intWeight;
			}
			set
			{
				if ((this._intWeight != value))
				{
					this.OnintWeightChanging(value);
					this.SendPropertyChanging();
					this._intWeight = value;
					this.SendPropertyChanged("intWeight");
					this.OnintWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intHeight", DbType="Int")]
		public System.Nullable<int> intHeight
		{
			get
			{
				return this._intHeight;
			}
			set
			{
				if ((this._intHeight != value))
				{
					this.OnintHeightChanging(value);
					this.SendPropertyChanging();
					this._intHeight = value;
					this.SendPropertyChanged("intHeight");
					this.OnintHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcImage", DbType="NVarChar(MAX)")]
		public string vcImage
		{
			get
			{
				return this._vcImage;
			}
			set
			{
				if ((this._vcImage != value))
				{
					this.OnvcImageChanging(value);
					this.SendPropertyChanging();
					this._vcImage = value;
					this.SendPropertyChanged("vcImage");
					this.OnvcImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStockKeepingUnits", DbType="Int")]
		public System.Nullable<int> intStockKeepingUnits
		{
			get
			{
				return this._intStockKeepingUnits;
			}
			set
			{
				if ((this._intStockKeepingUnits != value))
				{
					this.OnintStockKeepingUnitsChanging(value);
					this.SendPropertyChanging();
					this._intStockKeepingUnits = value;
					this.SendPropertyChanged("intStockKeepingUnits");
					this.OnintStockKeepingUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBarcode", DbType="NVarChar(MAX)")]
		public string vcBarcode
		{
			get
			{
				return this._vcBarcode;
			}
			set
			{
				if ((this._vcBarcode != value))
				{
					this.OnvcBarcodeChanging(value);
					this.SendPropertyChanging();
					this._vcBarcode = value;
					this.SendPropertyChanged("vcBarcode");
					this.OnvcBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAvailableQuantity", DbType="Int")]
		public System.Nullable<int> intAvailableQuantity
		{
			get
			{
				return this._intAvailableQuantity;
			}
			set
			{
				if ((this._intAvailableQuantity != value))
				{
					this.OnintAvailableQuantityChanging(value);
					this.SendPropertyChanging();
					this._intAvailableQuantity = value;
					this.SendPropertyChanged("intAvailableQuantity");
					this.OnintAvailableQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orderitem_order", Storage="_orders", ThisKey="intOrderItemID", OtherKey="intOrderItem")]
		public EntitySet<order> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				this._orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.orderitem = this;
		}
		
		private void detach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.orderitem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _intOrderID;
		
		private string _vcBuyerName;
		
		private string _vcBuyerPhone;
		
		private string _vcBuyerEmail;
		
		private string _vcShippingAddress;
		
		private System.Nullable<int> _intOrderStatus;
		
		private System.Nullable<int> _intOrderItem;
		
		private System.Nullable<int> _intQuantity;
		
		private EntityRef<orderitem> _orderitem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnintOrderIDChanging(int value);
    partial void OnintOrderIDChanged();
    partial void OnvcBuyerNameChanging(string value);
    partial void OnvcBuyerNameChanged();
    partial void OnvcBuyerPhoneChanging(string value);
    partial void OnvcBuyerPhoneChanged();
    partial void OnvcBuyerEmailChanging(string value);
    partial void OnvcBuyerEmailChanged();
    partial void OnvcShippingAddressChanging(string value);
    partial void OnvcShippingAddressChanged();
    partial void OnintOrderStatusChanging(System.Nullable<int> value);
    partial void OnintOrderStatusChanged();
    partial void OnintOrderItemChanging(System.Nullable<int> value);
    partial void OnintOrderItemChanged();
    partial void OnintQuantityChanging(System.Nullable<int> value);
    partial void OnintQuantityChanged();
    #endregion
		
		public order()
		{
			this._orderitem = default(EntityRef<orderitem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int intOrderID
		{
			get
			{
				return this._intOrderID;
			}
			set
			{
				if ((this._intOrderID != value))
				{
					this.OnintOrderIDChanging(value);
					this.SendPropertyChanging();
					this._intOrderID = value;
					this.SendPropertyChanged("intOrderID");
					this.OnintOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerName", DbType="NVarChar(100)")]
		public string vcBuyerName
		{
			get
			{
				return this._vcBuyerName;
			}
			set
			{
				if ((this._vcBuyerName != value))
				{
					this.OnvcBuyerNameChanging(value);
					this.SendPropertyChanging();
					this._vcBuyerName = value;
					this.SendPropertyChanged("vcBuyerName");
					this.OnvcBuyerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerPhone", DbType="NVarChar(50)")]
		public string vcBuyerPhone
		{
			get
			{
				return this._vcBuyerPhone;
			}
			set
			{
				if ((this._vcBuyerPhone != value))
				{
					this.OnvcBuyerPhoneChanging(value);
					this.SendPropertyChanging();
					this._vcBuyerPhone = value;
					this.SendPropertyChanged("vcBuyerPhone");
					this.OnvcBuyerPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerEmail", DbType="NVarChar(50)")]
		public string vcBuyerEmail
		{
			get
			{
				return this._vcBuyerEmail;
			}
			set
			{
				if ((this._vcBuyerEmail != value))
				{
					this.OnvcBuyerEmailChanging(value);
					this.SendPropertyChanging();
					this._vcBuyerEmail = value;
					this.SendPropertyChanged("vcBuyerEmail");
					this.OnvcBuyerEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcShippingAddress", DbType="NVarChar(MAX)")]
		public string vcShippingAddress
		{
			get
			{
				return this._vcShippingAddress;
			}
			set
			{
				if ((this._vcShippingAddress != value))
				{
					this.OnvcShippingAddressChanging(value);
					this.SendPropertyChanging();
					this._vcShippingAddress = value;
					this.SendPropertyChanged("vcShippingAddress");
					this.OnvcShippingAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderStatus", DbType="Int")]
		public System.Nullable<int> intOrderStatus
		{
			get
			{
				return this._intOrderStatus;
			}
			set
			{
				if ((this._intOrderStatus != value))
				{
					this.OnintOrderStatusChanging(value);
					this.SendPropertyChanging();
					this._intOrderStatus = value;
					this.SendPropertyChanged("intOrderStatus");
					this.OnintOrderStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderItem", DbType="Int")]
		public System.Nullable<int> intOrderItem
		{
			get
			{
				return this._intOrderItem;
			}
			set
			{
				if ((this._intOrderItem != value))
				{
					if (this._orderitem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnintOrderItemChanging(value);
					this.SendPropertyChanging();
					this._intOrderItem = value;
					this.SendPropertyChanged("intOrderItem");
					this.OnintOrderItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intQuantity", DbType="Int")]
		public System.Nullable<int> intQuantity
		{
			get
			{
				return this._intQuantity;
			}
			set
			{
				if ((this._intQuantity != value))
				{
					this.OnintQuantityChanging(value);
					this.SendPropertyChanging();
					this._intQuantity = value;
					this.SendPropertyChanged("intQuantity");
					this.OnintQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orderitem_order", Storage="_orderitem", ThisKey="intOrderItem", OtherKey="intOrderItemID", IsForeignKey=true)]
		public orderitem orderitem
		{
			get
			{
				return this._orderitem.Entity;
			}
			set
			{
				orderitem previousValue = this._orderitem.Entity;
				if (((previousValue != value) 
							|| (this._orderitem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orderitem.Entity = null;
						previousValue.orders.Remove(this);
					}
					this._orderitem.Entity = value;
					if ((value != null))
					{
						value.orders.Add(this);
						this._intOrderItem = value.intOrderItemID;
					}
					else
					{
						this._intOrderItem = default(Nullable<int>);
					}
					this.SendPropertyChanged("orderitem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spdisplay_allordersResult
	{
		
		private int _intOrderID;
		
		private string _vcBuyerName;
		
		private string _vcBuyerPhone;
		
		private string _vcBuyerEmail;
		
		private string _vcShippingAddress;
		
		private System.Nullable<int> _intOrderStatus;
		
		private System.Nullable<int> _intOrderItem;
		
		private System.Nullable<int> _intQuantity;
		
		public spdisplay_allordersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderID", DbType="Int NOT NULL")]
		public int intOrderID
		{
			get
			{
				return this._intOrderID;
			}
			set
			{
				if ((this._intOrderID != value))
				{
					this._intOrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerName", DbType="NVarChar(100)")]
		public string vcBuyerName
		{
			get
			{
				return this._vcBuyerName;
			}
			set
			{
				if ((this._vcBuyerName != value))
				{
					this._vcBuyerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerPhone", DbType="NVarChar(50)")]
		public string vcBuyerPhone
		{
			get
			{
				return this._vcBuyerPhone;
			}
			set
			{
				if ((this._vcBuyerPhone != value))
				{
					this._vcBuyerPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerEmail", DbType="NVarChar(50)")]
		public string vcBuyerEmail
		{
			get
			{
				return this._vcBuyerEmail;
			}
			set
			{
				if ((this._vcBuyerEmail != value))
				{
					this._vcBuyerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcShippingAddress", DbType="NVarChar(MAX)")]
		public string vcShippingAddress
		{
			get
			{
				return this._vcShippingAddress;
			}
			set
			{
				if ((this._vcShippingAddress != value))
				{
					this._vcShippingAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderStatus", DbType="Int")]
		public System.Nullable<int> intOrderStatus
		{
			get
			{
				return this._intOrderStatus;
			}
			set
			{
				if ((this._intOrderStatus != value))
				{
					this._intOrderStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderItem", DbType="Int")]
		public System.Nullable<int> intOrderItem
		{
			get
			{
				return this._intOrderItem;
			}
			set
			{
				if ((this._intOrderItem != value))
				{
					this._intOrderItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intQuantity", DbType="Int")]
		public System.Nullable<int> intQuantity
		{
			get
			{
				return this._intQuantity;
			}
			set
			{
				if ((this._intQuantity != value))
				{
					this._intQuantity = value;
				}
			}
		}
	}
	
	public partial class spdisplay_spcificorderResult
	{
		
		private int _intOrderID;
		
		private string _vcBuyerName;
		
		private string _vcBuyerPhone;
		
		private string _vcBuyerEmail;
		
		private string _vcShippingAddress;
		
		private System.Nullable<int> _intOrderStatus;
		
		private System.Nullable<int> _intOrderItem;
		
		private System.Nullable<int> _intQuantity;
		
		public spdisplay_spcificorderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderID", DbType="Int NOT NULL")]
		public int intOrderID
		{
			get
			{
				return this._intOrderID;
			}
			set
			{
				if ((this._intOrderID != value))
				{
					this._intOrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerName", DbType="NVarChar(100)")]
		public string vcBuyerName
		{
			get
			{
				return this._vcBuyerName;
			}
			set
			{
				if ((this._vcBuyerName != value))
				{
					this._vcBuyerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerPhone", DbType="NVarChar(50)")]
		public string vcBuyerPhone
		{
			get
			{
				return this._vcBuyerPhone;
			}
			set
			{
				if ((this._vcBuyerPhone != value))
				{
					this._vcBuyerPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcBuyerEmail", DbType="NVarChar(50)")]
		public string vcBuyerEmail
		{
			get
			{
				return this._vcBuyerEmail;
			}
			set
			{
				if ((this._vcBuyerEmail != value))
				{
					this._vcBuyerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcShippingAddress", DbType="NVarChar(MAX)")]
		public string vcShippingAddress
		{
			get
			{
				return this._vcShippingAddress;
			}
			set
			{
				if ((this._vcShippingAddress != value))
				{
					this._vcShippingAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderStatus", DbType="Int")]
		public System.Nullable<int> intOrderStatus
		{
			get
			{
				return this._intOrderStatus;
			}
			set
			{
				if ((this._intOrderStatus != value))
				{
					this._intOrderStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intOrderItem", DbType="Int")]
		public System.Nullable<int> intOrderItem
		{
			get
			{
				return this._intOrderItem;
			}
			set
			{
				if ((this._intOrderItem != value))
				{
					this._intOrderItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intQuantity", DbType="Int")]
		public System.Nullable<int> intQuantity
		{
			get
			{
				return this._intQuantity;
			}
			set
			{
				if ((this._intQuantity != value))
				{
					this._intQuantity = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
